Version: 1
Settings:
  Polling:
    Interval: 1s
Services:
  - Id: "sentinel-docker-demo-id"
    Name: "Docker-Demo"
    Type: "docker"
    Docker:
      Container: "sentinel-docker-demo"
  - Id: "sentinel-docker-demo2-id"
    Name: "Demo2"
    Type: "docker"
    Docker:
      Container: "sentinel-docker-demo2"
  - Id: "sentinel-systemd-demo-id"
    Name: "Systemd-Demo"
    Type: "systemd"
    Systemd:
      Unit: "sentinel-systemd-demo.service"
  - Id: "sentinel-k8s-demo-id"
    Name: "K8s-Demo"
    Type: "k8s"
    K8s:
      Context: "k3d-sentinel"
      Namespace: "sentinel-demo"
      Pod: "sentinel-k8s-demo"
